name: Shopware Plugin Verification

on:
  pull_request:
    branches: [main, develop]
  push:
    tags:
      - "v*.*.*"  

jobs:
  verify-plugin:
    name: Verify Shopware Plugin
    runs-on: ubuntu-latest  

    strategy:
      fail-fast: false
      matrix:
        version-selection: ['lowest', 'highest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check code style
        run: |
          docker run --rm -v $(pwd):/ext ghcr.io/shopwarelabs/extension-verifier:latest \
            check /ext --only php-cs-fixer --reporter github

      - name: Run Shopware Extension Verifier
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.version-selection }}

      - name: Fail on Verification Errors
        if: failure()
        run: exit 1
