name: Shopware Plugin Verification

on:
  pull_request:
    branches: [main, develop]
  push:
    branches:
      - '**'
    tags:
      - "v*.*.*"

jobs:
  verify-plugin:
    name: Verify Shopware Plugin
    runs-on: ubuntu-latest  

    strategy:
      fail-fast: false
      matrix:
        version-selection: ['lowest', 'highest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' 

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  
          tools: composer:v2

      - name: Allow Symfony Runtime Plugin
        run: composer config --no-plugins allow-plugins.symfony/runtime true
        
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Shopware Extension Verifier
        id: verifier
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.version-selection }}

      - name: ✅ Extension Verifier Passed – No errors found
        if: success() && steps.verifier.outcome == 'success'
        run: |
          echo "✅ Shopware Extension Verifier ran successfully. No issues found!"
          echo "### ✅ Shopware Extension Verifier Passed (${matrix.version-selection})" >> $GITHUB_STEP_SUMMARY

      - name: ❌ Extension Verifier Failed – Errors were found
        if: failure() && steps.verifier.outcome == 'failure'
        run: |
          echo "❌ Shopware Extension Verifier detected issues. Please review and fix them."
          echo "### ❌ Shopware Extension Verifier Failed (${matrix.version-selection})" >> $GITHUB_STEP_SUMMARY
          exit 1
